# vim: ft=yaml.ansible
---
# tasks file for redict

- name: "Create redict directories"
  become: true
  loop:
    - "{{ redict_base_path }}"
    - "{{ redict_data_path }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "1000"
    group: "1000"
    mode: "700"
    state: "directory"

- name: "Copy redict.conf"
  become: true
  notify:
    - "Restart redict"
  ansible.builtin.copy:
    dest: "{{ redict_config_path }}"
    src: "redict.conf"
    owner: "1000"
    group: "1000"
    mode: "400"

- name: "Create docker network for redict containers"
  become: true
  community.docker.docker_network:
    name: "{{ redict_network }}"
    driver: "bridge"
    scope: "local"
    state: "present"

- name: "Start redict container"
  become: true
  community.docker.docker_container:
    state: "started"
    name: "{{ redict_container_name }}"
    image: "{{ redict_image }}"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    network_mode: "{{ redict_network }}"
    networks:
      - name: "{{ redict_network }}"
        aliases:
          - "redict"
          - "redis"
    mounts:
      - source: "{{ redict_data_path }}"
        target: "/data"
        type: "bind"
      - source: "{{ redict_config_path }}"
        target: "/redict.conf"
        type: "bind"
        read_only: true
    command:
      - "/redict.conf"
