# vim: ft=yaml.ansible
---
# defaults file for nextcloud
nextcloud_asset_path: "{{ (service_base_path, 'asset') | path_join }}"
nextcloud_data_path: "{{ (service_base_path, 'data') | path_join }}"
nextcloud_domain: "nc.holi0317.net"
