# vim: ft=yaml.ansible
---
- name: "Install systemd units"
  become: true
  loop:
    - "restic.service"
    - "restic.timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    mode: "644"

- name: "Enable and start timer"
  become: true
  systemd:
    name: "restic.timer"
    daemon_reload: true
    enabled: true
    state: started
