---
galaxy_info:
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "ArchLinux"
      versions:
        - "any"

dependencies:
  - role: "bootstrap"
    vars:
      service_name: "peertube"
  - role: "postgres"
    vars:
      service_name: "peertube"
      postgres_user: "peertube"
  - role: "redis"
    vars:
      service_name: "peertube"
