---
galaxy_info:
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "ArchLinux"
      versions:
        - "any"

dependencies:
  - role: "bootstrap"
    vars:
      service_name: "photoprism"
  - role: "maria"
    vars:
      service_name: "photoprism"
      maria_user: "photoprism"
