---
# tasks file for gitea
- name: "Create gitea data directories"
  become: true
  file:
    path: "{{ gitea_data_dir }}"
    owner: "1000"
    group: "1000"
    mode: "755"
    state: "directory"

- name: "Create gitea container"
  become: true
  docker_container:
    state: "started"
    name: "{{ service_name }}_gitea"
    image: "gitea/gitea"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    network_mode: "{{ service_network }}"
    networks:
      - name: "{{ service_network }}"
      - name: "traefik"
    ports:
      - "{{ gitea_ssh_port }}:{{ gitea_ssh_port }}"
    env:
      USER_UID: "1000"
      USER_GID: "1000"

      SSH_PORT: "{{ gitea_ssh_port | string }}"
      START_SSH_SERVER: "true"

      LFS_START_SERVER: "true"

      DB_TYPE: "postgres"
      DB_HOST: "postgres:5432"
      DB_USER: "gitea"
      DB_PASSWD: "{{ postgres_password }}"

      DISABLE_REGISTRATION: "true"
      REQUIRE_SIGNIN_VIEW: "true"
      ROOT_URL: "https://{{ gitea_domain }}"
      RUN_MODE: "prod"

      GITEA__cache__ENABLED: "true"
      GITEA__cache__ADAPTER: "redis"
      GITEA__cache__HOST: "redis://redis:6379/0"

      GITEA__session__PROVIDER: "redis"
      GITEA__session__PROVIDER_CONFIG: "redis://redis:6379/1"

      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__FROM: "no-reply@{{ gitea_domain }}"
      GITEA__mailer__MAILER_TYPE: "smtp"
      GITEA__mailer__HOST: "{{ gitea_smtp_host }}"
      GITEA__mailer__IS_TLS_ENABLED: "true"
      GITEA__mailer__USER: "{{ gitea_smtp_user }}"
      GITEA__mailer__PASSWD: "{{ gitea_smtp_password }}"
      GITEA__service__ENABLE_NOTIFY_MAIL: "true"

    mounts:
      - source: "{{ gitea_data_dir }}"
        target: "/data"
        type: "bind"
    labels:
      traefik.enable: "true"
      traefik.http.services.gitea.loadbalancer.server.port: "3000"
      traefik.docker.network: "traefik"
      traefik.http.routers.gitea.rule: "Host(`{{ gitea_domain }}`)"
      traefik.http.routers.gitea.entrypoints: "websecure"
      traefik.http.routers.gitea.tls.certresolver: "myhttpchallenge"
      traefik.http.routers.gitea.middlewares: "compress@file,secure_head@file"
