---
galaxy_info:
  license: "MIT"
  min_ansible_version: "2.11"
  platforms:
    - name: "ArchLinux"
      versions:
        - "any"

dependencies:
  - role: "bootstrap"
    vars:
      service_name: "navidrome"
