# vim: ft=yaml.ansible
---
galaxy_info:
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "ArchLinux"
      versions:
        - "any"

dependencies:
  - role: "bootstrap"
    vars:
      service_name: "traefik"
      # This should disable docker network creation
      service_network: ""
