---
# tasks file for vikunja
- name: "Create vikunja data directories"
  become: true
  file:
    path: "{{ vikunja_data_dir }}"
    owner: "1000"
    group: "1000"
    mode: "755"
    state: "directory"

- name: "Create vikunja api container"
  become: true
  docker_container:
    state: "started"
    name: "{{ service_name }}_api"
    image: "vikunja/api"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    network_mode: "{{ service_network }}"
    networks:
      - name: "{{ service_network }}"
      - name: "traefik"
    env:
      PUID: "1000"
      PGID: "1000"

      VIKUNJA_SERVICE_JWT_SECRET: "{{ vikunja_jwt_secret }}"
      VIKUNJA_SERVICE_INTERFACE: ":3456"

      VIKUNJA_SERVICE_FRONTENDURL: "https://{{ vikunja_domain }}"
      VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"

      VIKUNJA_DATABASE_TYPE: "postgres"
      VIKUNJA_DATABASE_HOST: "postgres:5432"
      VIKUNJA_DATABASE_USER: "vikunja"
      VIKUNJA_DATABASE_PASSWORD: "{{ postgres_password }}"

      VIKUNJA_CACHE_ENABLED: "true"
      VIKUNJA_CACHE_TYPE: "redis"
      VIKUNJA_KEYVALUE_TYPE: "redis"
      VIKUNJA_REDIS_ENABLED: "true"
      VIKUNJA_REDIS_HOST: "redis:6379"

      VIKUNJA_MAILER_ENABLED: "true"
      VIKUNJA_MAILER_HOST: "{{ smtp_host }}"
      VIKUNJA_MAILER_PORT: "{{ smtp_port }}"
      VIKUNJA_MAILER_USERNAME: "{{ smtp_user }}"
      VIKUNJA_MAILER_PASSWORD: "{{ smtp_password }}"
      VIKUNJA_MAILER_FROMEMAIL: "no-reply@{{ vikunja_domain }}"

    mounts:
      - source: "{{ vikunja_data_dir }}"
        target: "/app/vikunja/files"
        type: "bind"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.vikunja-api.loadbalancer.server.port: "3456"
      traefik.http.routers.vikunja-api.rule: "Host(`{{ vikunja_domain }}`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
      traefik.http.routers.vikunja-api.entrypoints: "websecure"
      traefik.http.routers.vikunja-api.tls.certresolver: "myhttpchallenge"
      traefik.http.routers.vikunja-api.middlewares: "compress@file,secure_head@file"

- name: "Create vikunja frontend container"
  become: true
  docker_container:
    state: "started"
    name: "{{ service_name }}_frontend"
    image: "vikunja/frontend"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    network_mode: "{{ service_network }}"
    networks:
      - name: "{{ service_network }}"
      - name: "traefik"
    env:
      PUID: "1000"
      PGID: "1000"

    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.vikunja-frontend.loadbalancer.server.port: "80"
      traefik.http.routers.vikunja-frontend.rule: "Host(`{{ vikunja_domain }}`)"
      traefik.http.routers.vikunja-frontend.entrypoints: "websecure"
      traefik.http.routers.vikunja-frontend.tls.certresolver: "myhttpchallenge"
      traefik.http.routers.vikunja-frontend.middlewares: "compress@file,secure_head@file"
