# vim: ft=yaml.ansible
---
- import_tasks: "{{ role_path }}/tasks/fedora.yml"
  when: "ansible_facts['distribution'] == 'Fedora'"

- import_tasks: "{{ role_path }}/tasks/fedora.yml"
  when: "ansible_facts['distribution'] == 'Ubuntu'"

- name: "Start docker service"
  become: true
  service:
    name: "docker"
    state: "started"
    enabled: true
