# vim: ft=yaml.ansible
---
- name: "Import docker gpg key"
  become: true
  ansible.builtin.apt_key:
    key: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add docker repository"
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "Install docker packages"
  become: true
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - crun
    state: present
