# vim: ft=yaml.ansible
---
- import_tasks: "{{ role_path }}/tasks/check.yml"

- name: "Create cf-ddns base dir"
  become: true
  ansible.builtin.file:
    path: "{{ ddns_base_path }}"
    owner: "root"
    group: "root"
    mode: "755"
    state: "directory"

- name: "Create service docker network"
  become: true
  community.docker.docker_network:
    name: "{{ ddns_service_network }}"
    driver: "bridge"
    scope: "local"
    state: "present"

- name: "Create cf-ddns config file from template"
  become: true
  notify:
    - "Restart ddns"
  ansible.builtin.template:
    dest: "{{ ddns_conf_path }}"
    src: "cf-ddns.toml.j2"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "Create ddns container"
  become: true
  community.docker.docker_container:
    state: "started"
    name: "ddns"
    image: "registry.gitlab.com/holi0317/cf-ddns"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    network_mode: "{{ ddns_service_network }}"
    networks:
      - name: "{{ ddns_service_network }}"
    command: "--config /cf-ddns.toml --loglevel debug"
    mounts:
      - source: "{{ ddns_conf_path }}"
        target: "/cf-ddns.toml"
        type: "bind"
        read_only: true
