# vim: ft=yaml.ansible
---
# defaults file for postgres
postgres_version: "16"
postgres_image: "postgres:{{ postgres_version }}-alpine"
postgres_container_name: "postgres_postgres"
postgres_user: "postgres"
postgres_database: "{{ postgres_user }}"
postgres_password: ""
postgres_initdb_args: "--auth-host=scram-sha-256 --encoding=UTF8 --locale=en_US.UTF8"

postgres_base_path: "/srv/services/postgres"
postgres_data_path: "{{ (postgres_base_path, postgres_version) | path_join }}"
postgres_conf_path: "{{ (postgres_base_path, 'postgresql.conf') | path_join }}"
