# vim: ft=yaml.ansible
---
# tasks file for postgres
- import_tasks: "{{ role_path }}/tasks/check.yml"

- name: "Create postgres directories"
  become: true
  loop:
    - "{{ postgres_base_path }}"
    - "{{ postgres_data_path }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "70"
    group: "70"
    mode: "700"
    state: "directory"

- name: "Copy postgresql.confg"
  become: true
  ansible.builtin.copy:
    dest: "{{ postgres_conf_path }}"
    src: "postgresql.conf"
    owner: "70"
    group: "70"
    mode: "400"

- name: "Create docker network for postgres containers"
  become: true
  community.docker.docker_network:
    name: "postgres"
    driver: "bridge"
    scope: "local"
    state: "present"

- name: "Start postgres container"
  become: true
  community.docker.docker_container:
    state: "started"
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    pull: true
    comparisons:
      image: "strict"
      env: "strict"
      volumes: "allow_more_present"
      networks: "allow_more_present"

    # Prepare for docker plugin v2 change
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    read_only: false
    tty: false

    restart_policy: "always"
    user: "70:70"
    network_mode: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - name: "postgres"
        aliases:
          - "postgres"
    mounts:
      - source: "{{ postgres_data_path }}"
        target: "/var/lib/postgresql/data"
        type: "bind"
      - source: "{{ postgres_conf_path }}"
        target: "/etc/postgresql/postgresql.conf"
        type: "bind"
        read_only: true
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_database }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_INITDB_ARGS: "{{ postgres_initdb_args }}"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

    command:
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

# This assumes the docker command is targeting the same host as docker ansible modules.
# Which might not always be the case.
- name: "Wait for postgres to be up"
  become: true
  command: "docker exec {{ postgres_container_name|quote }} pg_isready"
  register: "pg_up"
  until: "pg_up.rc == 0"
  retries: 20
  delay: 3

- name: "Install psycopg2 via dnf"
  become: true
  ansible.builtin.dnf:
    name: "python3-psycopg2"
    state: "present"
