---
# Ansible task for creating mywg firewalld interface

- name: "Create mywg zone for containing wireguard interface"
  become: true
  register: "result"
  ansible.posix.firewalld:
    zone: "mywg"
    permanent: true
    target: "default"
    state: "present"

- name: "Reload firewalld"
  become: true
  when: "result.changed"
  systemd:
    name: "firewalld"
    state: "reloaded"

- name: "Bind mywg zone to wg0 wireguard interface"
  become: true
  ansible.posix.firewalld:
    zone: "mywg"
    permanent: true
    immediate: true
    interface: "wg0"
    state: "enabled"
